"""LLM clients and provider adapters."""

from vmp_memos.llm.base import ChatMessage, LLMGenerationConfig, LLMResponse
from vmp_memos.llm.candidate_planner import (
    LONGMEMEVAL_IDENTITY_CANDIDATE_PLANNER_VERSION,
    LONGMEMEVAL_V55_DUAL_VIEW_CANDIDATE_PLANNER_VERSION,
    LongMemEvalCandidatePlan,
    plan_longmemeval_rerank_candidates,
)
from vmp_memos.llm.reader import (
    LongMemEvalReader,
    LongMemEvalReaderConfig,
    ReaderOutput,
    build_longmemeval_prompt,
)
from vmp_memos.llm.reranker import (
    LONGMEMEVAL_ATOMIC_BOUNDARY_PROMPT_VERSION,
    LONGMEMEVAL_BOUNDARY_PROMPT_VERSION,
    LONGMEMEVAL_RERANK_PROMPT_VERSION,
    LONGMEMEVAL_SYMBOLIC_BOUNDARY_PROMPT_VERSION,
    LONGMEMEVAL_SYMBOLIC_SPAN_BOUNDARY_PROMPT_VERSION,
    LONGMEMEVAL_SYMBOLIC_SPAN_SELECTOR_PROMPT_VERSION,
    LONGMEMEVAL_V55_CHALLENGER_SELECTOR_PROMPT_VERSION,
    LONGMEMEVAL_V551_COMPLETE_CHALLENGER_SELECTOR_PROMPT_VERSION,
    LongMemEvalBoundaryDecision,
    LongMemEvalEvidenceReranker,
    LongMemEvalRerankDecision,
    LongMemEvalRerankerConfig,
    build_longmemeval_boundary_prompt,
    build_longmemeval_rerank_prompt,
    candidate_evidence_spans,
    candidate_excerpt,
    guarded_session_ranking,
    prepare_longmemeval_rerank_candidates,
    reorder_memories,
)
from vmp_memos.llm.selector_replay import (
    SelectorReplayCache,
    SelectorReplayClient,
    SelectorReplayEntry,
    SelectorReplayPreflight,
    load_selector_replay_cache,
    validate_selector_replay_source,
)
from vmp_memos.llm.vllm_client import VLLMClient, VLLMClientConfig, load_vllm_config

__all__ = [
    "LONGMEMEVAL_ATOMIC_BOUNDARY_PROMPT_VERSION",
    "LONGMEMEVAL_BOUNDARY_PROMPT_VERSION",
    "LONGMEMEVAL_IDENTITY_CANDIDATE_PLANNER_VERSION",
    "LONGMEMEVAL_RERANK_PROMPT_VERSION",
    "LONGMEMEVAL_SYMBOLIC_BOUNDARY_PROMPT_VERSION",
    "LONGMEMEVAL_SYMBOLIC_SPAN_BOUNDARY_PROMPT_VERSION",
    "LONGMEMEVAL_SYMBOLIC_SPAN_SELECTOR_PROMPT_VERSION",
    "LONGMEMEVAL_V55_CHALLENGER_SELECTOR_PROMPT_VERSION",
    "LONGMEMEVAL_V55_DUAL_VIEW_CANDIDATE_PLANNER_VERSION",
    "LONGMEMEVAL_V551_COMPLETE_CHALLENGER_SELECTOR_PROMPT_VERSION",
    "ChatMessage",
    "LLMGenerationConfig",
    "LLMResponse",
    "LongMemEvalBoundaryDecision",
    "LongMemEvalCandidatePlan",
    "LongMemEvalEvidenceReranker",
    "LongMemEvalReader",
    "LongMemEvalReaderConfig",
    "LongMemEvalRerankDecision",
    "LongMemEvalRerankerConfig",
    "ReaderOutput",
    "SelectorReplayCache",
    "SelectorReplayClient",
    "SelectorReplayEntry",
    "SelectorReplayPreflight",
    "VLLMClient",
    "VLLMClientConfig",
    "build_longmemeval_boundary_prompt",
    "build_longmemeval_prompt",
    "build_longmemeval_rerank_prompt",
    "candidate_evidence_spans",
    "candidate_excerpt",
    "guarded_session_ranking",
    "load_selector_replay_cache",
    "load_vllm_config",
    "plan_longmemeval_rerank_candidates",
    "prepare_longmemeval_rerank_candidates",
    "reorder_memories",
    "validate_selector_replay_source",
]
